/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitIdRouteImport } from './routes/produit.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitIdRoute = ProduitIdRouteImport.update({
  id: '/produit/$id',
  path: '/produit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/login': typeof LoginRoute
  '/panier': typeof PanierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/produit/$id': typeof ProduitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/login': typeof LoginRoute
  '/panier': typeof PanierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/produit/$id': typeof ProduitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/login': typeof LoginRoute
  '/panier': typeof PanierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/produit/$id': typeof ProduitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/catalogue'
    | '/contact'
    | '/favoris'
    | '/login'
    | '/panier'
    | '/sitemap.xml'
    | '/produit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/catalogue'
    | '/contact'
    | '/favoris'
    | '/login'
    | '/panier'
    | '/sitemap.xml'
    | '/produit/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/catalogue'
    | '/contact'
    | '/favoris'
    | '/login'
    | '/panier'
    | '/sitemap.xml'
    | '/produit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CatalogueRoute: typeof CatalogueRoute
  ContactRoute: typeof ContactRoute
  FavorisRoute: typeof FavorisRoute
  LoginRoute: typeof LoginRoute
  PanierRoute: typeof PanierRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProduitIdRoute: typeof ProduitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$id': {
      id: '/produit/$id'
      path: '/produit/$id'
      fullPath: '/produit/$id'
      preLoaderRoute: typeof ProduitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CatalogueRoute: CatalogueRoute,
  ContactRoute: ContactRoute,
  FavorisRoute: FavorisRoute,
  LoginRoute: LoginRoute,
  PanierRoute: PanierRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProduitIdRoute: ProduitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
